# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resourcelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planet',
            options={'ordering': ('-updated_at', 'name'), 'verbose_name': 'Planet', 'verbose_name_plural': 'Planets'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('-updated_at', 'title'), 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcelink',
            options={'ordering': ('-updated_at', 'title'), 'verbose_name': 'Resource Link', 'verbose_name_plural': 'Resources Links'},
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Slug Title'),
        ),
        migrations.AddField(
            model_name='resourcelink',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Slug Title'),
        ),
    ]
